// <auto-generated />
using System;
using Accountater.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Accountater.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(AccountaterDbContext))]
    [Migration("20250325001918_AddCsvImportSchemas")]
    partial class AddCsvImportSchemas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Accountater")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.AccountData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.CsvImportSchemaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CsvImportSchema", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.CsvImportSchemaMappingData", b =>
                {
                    b.Property<Guid>("ImportSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MappedProperty")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.HasKey("ImportSchemaId", "MappedProperty");

                    b.ToTable("CsvImportSchemaMapping", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.FinancialTransactionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transaction", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.TagData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Tag", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.TagRuleData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TagId");

                    b.ToTable("TagRule", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.TransactionTagData", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransactionTag", "Accountater");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.CsvImportSchemaMappingData", b =>
                {
                    b.HasOne("Accountater.Persistence.SqlServer.Models.CsvImportSchemaData", "ImportSchema")
                        .WithMany("Mappings")
                        .HasForeignKey("ImportSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportSchema");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.FinancialTransactionData", b =>
                {
                    b.HasOne("Accountater.Persistence.SqlServer.Models.AccountData", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.TagRuleData", b =>
                {
                    b.HasOne("Accountater.Persistence.SqlServer.Models.TagData", "Tag")
                        .WithMany("TagRules")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.TransactionTagData", b =>
                {
                    b.HasOne("Accountater.Persistence.SqlServer.Models.TagData", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Accountater.Persistence.SqlServer.Models.FinancialTransactionData", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.AccountData", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.CsvImportSchemaData", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("Accountater.Persistence.SqlServer.Models.TagData", b =>
                {
                    b.Navigation("TagRules");
                });
#pragma warning restore 612, 618
        }
    }
}
